### ISSUE TITLE
Tplink crashes

### ISSUE THREAD

**Issue by wemo666** [abaretta/nu.baretta.tplink#10]
Tplink crashes on homey ver 2.5.1. Whenever I click a uplink switch button and doesn’t work, I restart the tplink app, then it starts working again until next time. 

Regards

**Comment by abaretta** [comment]
Hi,

Whenever the app crashes, I receive a crash report. With the memory leak in Homey v2, all apps occasionally crash unfortunately. 

I haven’t seen an increase though, it’s been fairly quiet lately. I’ll keep an eye on it.
