### ISSUE TITLE
Just a note:

### ISSUE THREAD

**Issue by DaveGut** [abaretta/nu.baretta.tplink#4]
Wanted to pass a note.  First - the HS100 driver will work for the HS105, HS110, and HS200 also.

Second - check my site and the Hub or Cloud Based TP-Link to Smart Things..  I have updated some of the bulb commands based on discovery of 'ignore_defaults' which allows more sure control.  

Third - there are also emeter capabilities in the LB110, 120, and 130.  Uses slightly different calculation (milliWatts vice Watts), but is essentially the same code base.  I have the (groovy) algorithms in the device handlers.

Lastly, I have been looking for a command for determining run-time statistics by day, week, and month.  The firmware has runtime; however, I do not know how to invoke.  If you find this, I would be a very happy camper.

**Comment by gastonsl** [comment]
I am trying to create the a new app from code as the instructions mentioned for (BETA) TP-Link LB100 and LB110 Cloud-connect Device Handler

When I do create , I get the following error

No signature of method: script15038476829191434531170.metadata() is applicable for argument types: (script15038476829191434531170$_run_closure1) values: [script15038476829191434531170$_run_closure1@8b3aec6] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by DaveGut** [comment]
Closed as not an issue.
