### ISSUE TITLE
Error when creating smart app from code for (BETA) TP-Link LB100 and LB110 Cloud-connect Device Handler

### ISSUE THREAD

**Issue by gastonsl** [abaretta/nu.baretta.tplink#5]
I am trying to create a new app from code as the instructions mentioned for (BETA) TP-Link LB100 and LB110 Cloud-connect Device Handler

When I do create , I get the following error

No signature of method: script15038476829191434531170.metadata() is applicable for argument types: (script15038476829191434531170$_run_closure1) values: [script15038476829191434531170$_run_closure1@8b3aec6] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by abaretta** [comment]
A bit late, but this is not the place for questions about other code. I suggest you direct your question to people developing for the same platform or stackoverflow.
