### ISSUE TITLE
HS110 variables not available

### ISSUE THREAD

**Issue by northseer** [abaretta/nu.baretta.tplink#6]
I have just added an HS110 to a reasonably extensive - and well-functioning - Homey system but I find that the power, power meter and voltage variables are not appearing. There are no directly selectable options when setting up a flow apart from on/off. The tags themselves are available in the drop down but they stay unused and when inserted in a condition they remain undefined. I used the HS110 option when selecting the device for linking to the system. It has a static address. I have no other TP-link devices on this system - mainly Z-wave switches and sensors.

I have re-installed the device, checked the static IP address, and re-installed the app. Does this sound like a faulty device or is it more like a software issue and if so, is there a plan to address it?

**Comment by abaretta** [comment]
Thanks for reporting. This is a known issue and fixed in the latest release.

**Comment by northseer** [comment]
Thanks for the reply. I will update the app.

Regards

northseer
