### ISSUE TITLE
[Bug] Homey 2.0 - Powerdraw & usage is not updated 

### ISSUE THREAD

**Issue by Radiotechniman** [abaretta/nu.baretta.tplink#7]
The powerdraw & usage is read at the moment of pairing, after that not anymore

**Comment by pjmpessers** [comment]
For me the same problem. No read out of powerdraw and usage on HS-110 with homey firmware v2.0.0. I have TP-link smart devices app v0.0.017 installed. Restarting the app doesn't help. I uninstalled and installed the apps back and the powerdraw and usage was back for a moment. Until i restarted homey. Now the powerdraw and usage stays fixed on, let say, 0.49w and will not be updated. So the problem came back after restart of homey.

**Comment by robiebab** [comment]
For me the same, i have the hs-110. It doesn’t update the powerdraw.

**Comment by pjmpessers** [comment]
Every appliance connected on the network has a static ip- address in my network. But i noticed that when changing the ip- address of the hs-110 in homey and then back to the original ip- address gives the energy monitoring back. Until i restart homey. Then i must do the same thing all over again. Switching the hs-110 on/off always work. This solution is only for the energy monitoring.

**Comment by abaretta** [comment]
As I haven't updated to Homey v2 yet I can't investigate these issues. However, I will shortly publish the SDK2 update of the app, which may (or may not) fix the issues.

BTW, this update supports dynamic IP's. I am going to close this issue, please let me know if the issue also occurs the in upcoming SDK2 version (v0.1.0) when it appears in the store.

**Comment by Radiotechniman** [comment]
Just installed the github version, everything seems to be working 

thanks !

**Comment by pjmpessers** [comment]
Also installed the github version. And almost everything works great. Only there is no powerusage (energiemeter) read out for the HS-110.

**Comment by abaretta** [comment]
@Radiotechniman, do you have an hs110 as well? Does the power/energie metering work? 

It works fine on Homey 1.5.13 🤔 

@pjmpessers, any difference after restarting the app? Or doing a PTP (‘pull the plug’) on Homey? Final thing to try would be to re-pair the device. This does require first removing it, breaking any flows in which it is used. 

There are still quite a few issues in Homey v2, I am guessing this is one of them :-/

**Comment by pjmpessers** [comment]
Thank you for your help abaretta. I did a ptp but it didn't help. So i removed and installed with node.js the app back. I got a powerusage read out back but while all the other read out keeps refreshing every few seconds the powerusage is only reading it out ones and doesn't update it anymore.

**Comment by pjmpessers** [comment]
@abaretta. It looks like powerusage does update. So everything looks to be working. I let you know if anything change. Thanks.

**Comment by abaretta** [comment]
Nice! Glad to hear it, thanks for the update 👍

**Comment by Radiotechniman** [comment]
> @Radiotechniman, do you have an hs110 as well? Does the power/energie metering work?
> 
Yes I have the HS110 (9 of them) and running Homey 2.0, started with the RC's
