### ISSUE TITLE
Homey 2.0.0 issue

### ISSUE THREAD

**Issue by rafi1975** [abaretta/nu.baretta.tplink#8]
I just updated Homey to v. 2.0.0 and can't control my TP-Link HS-110 Smart Plugs. They are seen by the app by the turn off/on functionality is not working at all.

**Comment by abaretta** [comment]
I haven't updated to v2.0 yet, so I can't do much about this. That is, other than publishing the SDK2 version shortly (v0.1.0). It may solve the issue, or it may not. There are no special features in the app, we'll see...

I will submit it to the app store in a few days, however at the moment the approval process takes a looong time. 

I am going to close this issue, please let me know if v0.1.0 still has the same issue once the app is published in the store.
